# Generated by Django 5.2.5 on 2025-08-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
