# Generated by Django 5.2.6 on 2025-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
